# https://docs.coderabbit.ai/getting-started/configure-coderabbit/?#configure-coderabbit-using-a-yaml-file
---
language: en-US
early_access: false
enable_free_tier: true
reviews:
  sequence_diagrams: false
  poem: false
  auto_review:
    base_branches:
      - main
      - stable
      # opendatahub-io/notebooks
      - 2024a
      - 2024b
      # red-hat-data-services/notebooks
      - rhoai-.*
      - release-.*
