---
# https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#hooks-available
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  # https://docs.astral.sh/uv/guides/integration/pre-commit/
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.18
    hooks:
      - id: uv-lock
  # https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        types_or: [python, pyi, jupyter]
        args: [--fix]
        files: '^((ci|tests|ntb|base-images)/.*\.(py|pyi)|jupyter/.*\.ipynb)$'
      - id: ruff-format
        types_or: [python, pyi]
        files: '^(ci|tests|ntb|base-images)/.*\.(py|pyi)$'
  # https://github.com/gitleaks/gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
  # https://pre-commit.com/#new-hooks
  - repo: local
    hooks:
      # https://github.com/microsoft/pyright/issues/3612
      # https://github.com/RobertCraigie/pyright-python#pre-commit
      - id: pyright
        name: Run Pyright on all files
        # entry: /bin/bash -c 'find. -name "*.py" | xargs pyright --pythonversion 3.12'
        entry: uv run pyright --pythonversion 3.12
        pass_filenames: true
        types_or: [python, pyi]
        language: system
        files: 'ci/.*|tests/.*'
