# RHOAI 3.3 Konflux build (hybrid hermetic=false). Keep AIPCC CPU base; Python from public PyPI at build time.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.3.5-1791232133@sha256:dcd12350c694e608d310df15caffeb4c09279a038e2893a2f8939d56d11a56d8
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-codeserver-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.3
