# RHOAI 3.3 Konflux build (hybrid hermetic=false). Keep AIPCC CPU base; Python from public PyPI at build time.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.3.4-1790276901@sha256:c6fdb5d4541ce0535f347b43401c03b954f68d9bfb257393b882ddd1f2160220
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-codeserver-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.3
