INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cpu-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.4.1-1780598682
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-codeserver-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.4
