# Base Image   : RHEL 9.6 with Python 3.12
# CUDA Version : 12.9
# Architectures: linux/arm64, linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/cuda
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.3.0-1768412345@sha256:db69f0e5533000bddefbc229f8eb79e3a01b8e175997753022d2a684d7d2d810
