# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cpu-py312-c9s:latest@sha256:5e3611a7e246ce586f7c758c62d0e7a4e5acb2290803941f65a0eebe9a0816c6
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-workbench-jupyter-datascience-cpu-py312-ubi9
PRODUCT=odh
RELEASE=3.5
