# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cpu:3.5.0-1786048153@sha256:78a2d9dce3031f792bf5bc07f42452bef1fabfba00ec1028bca4dc1bb2a10b97
PYLOCK_FLAVOR=cpu
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-workbench-jupyter-datascience-cpu-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
