# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/rocm-7.14-el9.6:3.5.0-1786048067@sha256:f5df37d972397cc3256b8bc392f1c035b995b0437c4c5f48b81f88eb4a6147ec
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
