# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-rocm-py312-c9s:v7.14@sha256:f32f8e15e57e02acf1244753bda49925133b1ea41dada98ae88cc7810882df1f
PYLOCK_FLAVOR=rocm
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-pytorch-rocm-py312-ubi9
PRODUCT=odh
RELEASE=3.5
