# Base Image   : RHEL 9.6 with Python 3.12
# ROCm Version : 6.3.4
# Architectures: linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/rocm
BASE_IMAGE=quay.io/aipcc/base-images/rocm:3.0-1755080929@sha256:d089897c2f7267446bde3f9edd354a78d9781e79bec482014592d31ddc80089a
