# Base Image   : RHEL 9.6 with Python 3.12
# ROCm Version : 6.3.4
# Architectures: linux/x86_64
# Source       : registry.redhat.io/rhai/base-image-rocm-rhel9
BASE_IMAGE=registry.redhat.io/rhai/base-image-rocm-rhel9:3.0.3-1790276886@sha256:37e4ee30c36a5750581dd9ab84c4908585359962e66c1280b6df1c932ce917c8
