INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cuda13.0-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cuda-13.0-el9.6:3.4.2-1789137658@sha256:f95c326c2436b89c0ed0bfa6e0f6486d49c9551a8b1616abccc0c9aefd23be2c
PYLOCK_FLAVOR=cuda
