# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/opendatahub/odh-base-image-cuda-py312-c9s:v12.9@sha256:83bfd2f484ed5c1a3df0544f96a286af53e03997d84e2fec40a66187fc4a6064
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=opendatahub
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-ubi9
PRODUCT=odh
RELEASE=3.5
