# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.0-1786048150@sha256:e0256407f4f47dc5908d7939a328368d136e923491735f833e869337b700f93f
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
