# To update `BASE_IMAGE` edit `versions_config.yml` and run `gmake sync-build-args-from-versions`
# For more information, see `docs/base_image_versions_update_configuration.md`.
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.5.2-1791231736@sha256:62834e5eaa959bb57d5c624bdc7192253a5cec69e91c1407ae7d60d21be539de
PYLOCK_FLAVOR=cuda
LABEL_REGISTRY_PREFIX=rhoai
LABEL_COMPONENT=odh-pipeline-runtime-tensorflow-cuda-py312-rhel9
PRODUCT=rhoai
RELEASE=3.5
