# RH wheel-only overlay for runtime-minimal public PyPI pylock.toml.
# Patched by: scripts/lockfile-generators/helpers/patch-rh-wheel-only-packages.py merge-be

[[packages]]
name = "pyzmq"
version = "27.2.0"
marker = "python_full_version == '3.12.*' and implementation_name == 'cpython' and sys_platform == 'linux'"
wheels = [
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.3/cpu-ubi9-test/pyzmq-27.2.0-2-cp312-cp312-linux_ppc64le.whl", size = 266722, hashes = { sha256 = "a2122ab49c11c7a86bba22e058720d5d40fbd7bf22673f614bb06d1471459cd7" } },
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.3/cpu-ubi9-test/pyzmq-27.2.0-2-cp312-cp312-linux_s390x.whl", size = 310879, hashes = { sha256 = "9750921ebe3686580c3e456d37c8503b8332b8ae16decafa2a39e8496886e224" } },
]
