# Base Image   : RHEL 9.6 with Python 3.12
# CUDA Version : 12.9
# Architectures: linux/arm64, linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/cuda
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.3.4-1790276833@sha256:686f07b133d3b219c2a65263bd5fad42ebcd4ccb79f7f1b59cb25f6464d84ce9
