# Base Image   : RHEL 9.6 with Python 3.12
# ROCm Version : 6.4
# Architectures: linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/rocm
BASE_IMAGE=quay.io/aipcc/base-images/rocm-6.4-el9.6:3.3.0-1768412209@sha256:c75d608241979484c9e73a546cfaac8fcc5dd500d3396e4e2bc2e3c8b7789958
