# Base Image   : RHEL 9.6 with Python 3.12
# ROCm Version : 6.3.4
# Architectures: linux/x86_64
# Source       : registry.redhat.io/rhai/base-image-rocm-rhel9
BASE_IMAGE=registry.redhat.io/rhai/base-image-rocm-rhel9:1782928977@sha256:60dc3070c54ac81c94c17e3cfad3c93eb3ab112f15783c824836bdf10583adb3
