# RH wheel-only overlay for pytorch public PyPI pylock.toml.
# pandoc-rhai is RH-index-only; patched by: scripts/lockfile-generators/helpers/patch-rh-wheel-only-packages.py replace

[[packages]]
name = "pandoc-rhai"
version = "3.9.0.2"
marker = "python_full_version == '3.12.*' and implementation_name == 'cpython' and sys_platform == 'linux'"
wheels = [
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9/pandoc_rhai-3.9.0.2-4-py3-none-linux_aarch64.whl", upload-time = 2026-06-18T07:23:56Z, size = 77522087, hashes = { sha256 = "8eef0dccbd3e9a9de54c0179e6bbc4140fe6c33407b0b2ec48686b990d817902" } },
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9/pandoc_rhai-3.9.0.2-4-py3-none-linux_ppc64le.whl", upload-time = 2026-06-18T07:24:11Z, size = 77077642, hashes = { sha256 = "9d902dc54ab361a59ba3a2f87668a7426be87a15691d235dbe78400c3a6a7f95" } },
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9/pandoc_rhai-3.9.0.2-4-py3-none-linux_s390x.whl", upload-time = 2026-06-18T07:39:30Z, size = 166817497, hashes = { sha256 = "40f0c5e3a9a971fe374fbb1d5f37a55adcbe6559ba40f800c948dd52043f14ec" } },
    { url = "https://packages.redhat.com/api/pulp-content/public-rhai/rhoai/3.5/cpu-ubi9/pandoc_rhai-3.9.0.2-4-py3-none-linux_x86_64.whl", upload-time = 2026-06-18T07:23:43Z, size = 65861027, hashes = { sha256 = "195086bd39f4724ac02e22187290808cbe19c60a0471a6c9108b4a6da1373947" } },
]
