# Base Image   : RHEL 9.6 with Python 3.12
# CUDA Version : 12.8.1
# Architectures: linux/arm64, linux/x86_64
# Source       : registry.redhat.io/rhai/base-image-cuda-rhel9
BASE_IMAGE=registry.redhat.io/rhai/base-image-cuda-rhel9:3.0.4-1790703567@sha256:41022d193ce3fbd099679fce910d86f2c3adfd780be6d9b1def88ce32005ecc8
