# Base Image   : RHEL 9.6 with Python 3.12
# CUDA Version : 12.8.1
# Architectures: linux/arm64, linux/x86_64
# Source       : https://quay.io/repository/aipcc/base-images/cuda
BASE_IMAGE=quay.io/aipcc/base-images/cuda:3.0-1756380241@sha256:549416e2cca57191d7bf9216069a4544255533af72e97febbeed4dd05cc78df9
