INDEX_URL=https://console.redhat.com/api/pypi/public-rhai/rhoai/3.4/cuda12.9-ubi9/simple/
BASE_IMAGE=quay.io/aipcc/base-images/cuda-12.9-el9.6:3.4.4-1791231926@sha256:48706c1e5fc3c71fb16709e1a691f631bb3bf13edf9eab4dabcefe1a1ab2525c
PYLOCK_FLAVOR=cuda
