apiVersion: tekton.dev/v1
kind: PipelineRun
# retrigger Konflux builds to fix https://issues.redhat.com/browse/RHOAIENG-31914
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/red-hat-data-services/notebooks?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-comment: "^/(build-konflux|build-codeserver)"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && target_branch == "main" &&
      !("manifests/base/params-latest.env".pathChanged()) &&
      (
        ".tekton/odh-workbench-codeserver-datascience-cpu-py312-pull-request.yaml".pathChanged() ||
        "codeserver/ubi9-python-3.12/**".pathChanged() ||
        "codeserver/ubi9-python-3.12/build-args/cpu.conf".pathChanged()
      ) && body.repository.full_name == "red-hat-data-services/notebooks"
  labels:
    appstudio.openshift.io/application: automation
    appstudio.openshift.io/component: pull-request-pipelines-notebooks
    pipelines.appstudio.openshift.io/type: build
  name: odh-workbench-codeserver-datascience-cpu-py312-on-pull-request-75964
  namespace: rhoai-tenant
spec:
  timeouts:
    pipeline: 8h0m0s
    tasks: "4h0m0s"
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: enable-cache-proxy
    value: "true"
  - name: hermetic
    value: "true"
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/rhoai/pull-request-pipelines:notebooks-{{revision}}
  - name: additional-tags
    value:
    - '{{target_branch}}-{{revision}}'
  - name: additional-labels
    value:
    - version=on-pr-{{revision}}
    - io.openshift.tags=odh-workbench-codeserver-datascience-cpu-py312
  - name: dockerfile
    value: codeserver/ubi9-python-3.12/Dockerfile.konflux.cpu
  - name: build-args-file
    value: codeserver/ubi9-python-3.12/build-args/konflux.cpu.conf
  - name: path-context
    value: .
  - name: build-image-index
    value: true
  - name: build-platforms
    value:
    - linux-d160-m8xlarge/amd64
    - linux-d160-m8xlarge/arm64
    - linux/ppc64le
    - linux/s390x
  - name: image-expires-after
    value: 5d
  - name: enable-slack-failure-notification
    value: "false"
  - name: prefetch-input
    value:
    - path: codeserver/ubi9-python-3.12/prefetch-input/rhds
      type: rpm
    - path: codeserver/ubi9-python-3.12/prefetch-input/rhds
      type: generic
    - path: codeserver/ubi9-python-3.12
      type: pip
      binary:
        arch: "x86_64,aarch64,ppc64le"
      requirements_files: ["requirements.cpu.txt"]
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/.vscode/extensions/vscode-selfhost-import-aid
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/.vscode/extensions/vscode-selfhost-test-provider
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/build
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/build/npm/gyp
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/configuration-editing
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/css-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/css-language-features/server
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/debug-auto-launch
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/debug-server-ready
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/emmet
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/extension-editing
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/git
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/git-base
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/github
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/github-authentication
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/grunt
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/gulp
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/html-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/html-language-features/server
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/ipynb
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/jake
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/json-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/json-language-features/server
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/markdown-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/markdown-math
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/media-preview
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/merge-conflict
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/mermaid-chat-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/notebook-renderers
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/npm
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/php-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/references-view
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/simple-browser
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/tunnel-forwarding
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/typescript-language-features
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/vscode-api-tests
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/vscode-colorize-perf-tests
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/vscode-colorize-tests
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/extensions/vscode-test-resolver
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/remote
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/remote/web
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/test/automation
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/test/integration/browser
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/test/mcp
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/test/monaco
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/lib/vscode/test/smoke
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server/test/e2e/extensions/test-extension
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/code-server
      type: npm    
    # patches/
    - path: codeserver/ubi9-python-3.12/prefetch-input/patches/code-server-v4.106.3/lib/vscode
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/patches/code-server-v4.106.3/test
      type: npm
    - path: codeserver/ubi9-python-3.12/prefetch-input/patches/code-server-v4.106.3/lib/vscode/extensions/microsoft-authentication
      type: npm
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/red-hat-data-services/konflux-central.git
    - name: revision
      value: '{{ target_branch }}'
    - name: pathInRepo
      value: pipelines/multi-arch-container-build.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-pull-request-pipelines
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
