---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: codeserver-
resources:
  - pod.yaml
images:
  - name: codeserver-workbench
    newName: quay.io/modh/codeserver
    newTag: codeserver-rhel-python-3.9
