---
name: Post-Codefreeze Gatekeeper

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled]
    branches:
      - 'rhoai-[0-9].[0-9]*'
jobs:
  post-codefreeze-gate:
    if: github.event.action != 'labeled' || github.event.label.name == 'run-gatekeeper'
    uses: red-hat-data-services/devops-shared-resources/.github/workflows/post-codefreeze-gate-logic.yml@f140b2f4770d56a9c9e7cbccec0f04fe43f08c2d  # main
    secrets: inherit
