---
name: Post-Codefreeze Gatekeeper

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled]
    branches:
      - 'main'
      - 'rhoai-[0-9].[0-9]*'
jobs:
  post-codefreeze-gate:
    if: github.event.action != 'labeled' || github.event.label.name == 'run-gatekeeper'
    uses: red-hat-data-services/devops-shared-resources/.github/workflows/post-codefreeze-gate-logic.yml@f7a7a3a173154a8c2cc353acd8c63bb57dac4efb  # main
    secrets: inherit
