---
name: Post-Codefreeze Gatekeeper
"on":
  pull_request_target:
    types: [opened, synchronize, reopened, edited, labeled]
    branches:
      - 'rhoai-3.5'
jobs:
  post-codefreeze-gate:
    if: github.event.action != 'labeled' || github.event.label.name == 'run-gatekeeper'
    uses: red-hat-data-services/devops-shared-resources/.github/workflows/post-codefreeze-gate-logic.yml@2930a6bea48c0f840e814b9333ab67591d7c5ab0  # main
    secrets: inherit
